# Generated by Django 5.1.4 on 2024-12-27 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='CreateForum',
        ),
    ]
